package com.medpulse.config;

import com.medpulse.model.*;
import com.medpulse.repository.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.List;
import java.util.Set;

@Component
@Slf4j
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {

    private final UserRepository userRepository;
    private final MedicalDepartmentRepository departmentRepository;
    private final PatientTriageCaseRepository patientCaseRepository;
    private final DoctorRepository doctorRepository;
    private final AppointmentRepository appointmentRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    public void run(String... args) {
        try {
            seedDoctorsAndAppointments();
            seedClinicalPlatformData();
        } catch (Exception e) {
            log.warn("Warning: Initial database seeding skipped or encountered an issue: {}", e.getMessage());
        }
    }

    private void seedClinicalPlatformData() {
        if (userRepository.count() > 0) {
            log.info("MedPulse clinical users and departments already initialized.");
            return;
        }

        log.info("Seeding MedPulse AI Clinical Healthcare demo data...");

        // 1. Seed Core Role Accounts (Patient, Doctor, Hospital, Admin)
        userRepository.save(User.builder()
                .fullName("Rameshwar Sharma")
                .email("patient@medplus.com")
                .phone("+91 98350 21984")
                .password(passwordEncoder.encode("password123"))
                .role(Role.ROLE_PATIENT)
                .build());

        userRepository.save(User.builder()
                .fullName("John Doe")
                .email("patient@medpulse.ai")
                .phone("+91 98765 43210")
                .password(passwordEncoder.encode("password123"))
                .role(Role.ROLE_PATIENT)
                .build());

        User doctor = userRepository.save(User.builder()
                .fullName("Dr. Navneet Kumar")
                .email("doctor@medplus.com")
                .phone("+91 94312 00111")
                .password(passwordEncoder.encode("password123"))
                .role(Role.ROLE_DOCTOR)
                .doctorId(1L)
                .hospital("Dr. Navneet Kumar Specialist Clinic")
                .departmentName("Physician / Neuro, Diabetes, Liver & Thyroid")
                .medicalLicense("MCI-8420-NK")
                .build());

        userRepository.save(User.builder()
                .fullName("Dr. Navneet Kumar")
                .email("doctor@medpulse.ai")
                .phone("+91 94312 00111")
                .password(passwordEncoder.encode("password123"))
                .role(Role.ROLE_DOCTOR)
                .doctorId(1L)
                .hospital("Dr. Navneet Kumar Specialist Clinic")
                .departmentName("Physician / Neuro, Diabetes, Liver & Thyroid")
                .medicalLicense("MCI-8420-NK")
                .build());

        User nurse = userRepository.save(User.builder()
                .fullName("Elena Rostova, BSN RN")
                .email("nurse@medpulse.ai")
                .phone("+91 94312 99887")
                .password(passwordEncoder.encode("password123"))
                .role(Role.ROLE_TRIAGE_NURSE)
                .medicalLicense("RN-73910-ER")
                .departmentName("Triage & Rapid Assessment")
                .build());

        userRepository.save(User.builder()
                .fullName("AIIMS Patna Facility Administration")
                .email("hospital@medplus.com")
                .phone("+91 612 245 1070")
                .password(passwordEncoder.encode("password123"))
                .role(Role.ROLE_HOSPITAL)
                .hospital("AIIMS Patna")
                .departmentName("Hospital Administration & Resource Allocation")
                .medicalLicense("HOSP-AIIMS-PAT")
                .build());

        userRepository.save(User.builder()
                .fullName("Prasad Hospital Administration")
                .email("hospital@medpulse.ai")
                .phone("+91 621 224 5566")
                .password(passwordEncoder.encode("password123"))
                .role(Role.ROLE_HOSPITAL)
                .hospital("Prasad Hospital")
                .departmentName("Hospital Operations")
                .medicalLicense("HOSP-REG-4821")
                .build());

        userRepository.save(User.builder()
                .fullName("Anas Siddiqui (System Administrator)")
                .email("admin@medplus.com")
                .phone("+91 98765 00000")
                .password(passwordEncoder.encode("password123"))
                .role(Role.ROLE_ADMIN)
                .departmentName("Central Health Network Administration")
                .medicalLicense("ADMIN-ROOT-01")
                .build());

        userRepository.save(User.builder()
                .fullName("Anas Siddiqui (Administrator)")
                .email("admin@medpulse.ai")
                .phone("+91 98765 00000")
                .password(passwordEncoder.encode("password123"))
                .role(Role.ROLE_ADMIN)
                .departmentName("Hospital Informatics")
                .medicalLicense("SYS-ADMIN-01")
                .build());

        // 2. Seed Medical Departments
        MedicalDepartment edTrauma = departmentRepository.save(MedicalDepartment.builder()
                .name("Emergency & Level 1 Trauma Center")
                .code("ED-TRAUMA")
                .specialty("Emergency Medicine")
                .headPhysician("Dr. Sarah Chen, MD")
                .bedCapacity(28)
                .currentOccupancy(21)
                .acuityLevel("Critical Level 1 (Resuscitation)")
                .description("Primary portal for high-acuity polytrauma, cardiac arrests, acute surgical emergencies, and rapid stabilization.")
                .clinicalProtocols(Set.of("ACLS", "ATLS", "Massive Transfusion Protocol (MTP)", "Rapid Sequence Intubation", "STEMI Door-to-Balloon"))
                .build());

        departmentRepository.save(MedicalDepartment.builder()
                .name("Cardiology & Hemodynamics ICU")
                .code("CARDIO-ICU")
                .specialty("Cardiovascular Medicine")
                .headPhysician("Dr. Marcus Vance, FACC")
                .bedCapacity(16)
                .currentOccupancy(13)
                .acuityLevel("Critical Level 1")
                .description("Intensive cardiac care unit equipped for post-angioplasty monitoring, cardiogenic shock, and ventricular arrhythmias.")
                .clinicalProtocols(Set.of("Cath Lab Stat Activation", "12-Lead Continuous ECG", "Heparin Titration", "Cardioversion Protocol"))
                .build());

        MedicalDepartment neuroStroke = departmentRepository.save(MedicalDepartment.builder()
                .name("Neurology & Comprehensive Stroke Center")
                .code("NEURO-STROKE")
                .specialty("Neurology & Neurocritical Care")
                .headPhysician("Dr. Aisha Patel, MD")
                .bedCapacity(14)
                .currentOccupancy(10)
                .acuityLevel("Emergent Level 2")
                .description("Dedicated hyper-acute stroke unit with 24/7 neurovascular imaging, IV thrombolysis, and endovascular thrombectomy capability.")
                .clinicalProtocols(Set.of("Code Stroke Protocol", "IV Tenecteplase / tPA", "Continuous NIHSS Scoring", "Emergency CT Angiography"))
                .build());

        departmentRepository.save(MedicalDepartment.builder()
                .name("Pulmonology & Respiratory Care Unit")
                .code("PULMO-CARE")
                .specialty("Pulmonology")
                .headPhysician("Dr. David Kim, FCCP")
                .bedCapacity(18)
                .currentOccupancy(12)
                .acuityLevel("Urgent Level 3")
                .description("Comprehensive inpatient respiratory unit managing acute exacerbations of asthma, severe COPD, and pneumonia.")
                .clinicalProtocols(Set.of("High-Flow Nasal Cannula (HFNC)", "BiPAP Titration", "Continuous Nebulizer Therapy", "Arterial Blood Gas (ABG)"))
                .build());

        departmentRepository.save(MedicalDepartment.builder()
                .name("Pediatric Care & Neonatal ICU")
                .code("PED-ICU")
                .specialty("Pediatrics")
                .headPhysician("Dr. Rachel Gomez, MD")
                .bedCapacity(12)
                .currentOccupancy(7)
                .acuityLevel("Emergent Level 2")
                .description("Specialized pediatric unit providing age-tailored acute care, pediatric resuscitation, and respiratory support.")
                .clinicalProtocols(Set.of("PALS Resuscitation", "Weight-Based Pediatric Dosing", "Pediatric Sepsis Bundle", "Asthma Pathway"))
                .build());

        Doctor clinicalDoctor = doctorRepository.findAll().isEmpty() ? null : doctorRepository.findAll().get(0);

        // 3. Seed Clinical Patient Triage Cases
        patientCaseRepository.save(PatientTriageCase.builder()
                .patientId("PT-9401")
                .patientName("John Doe")
                .age(58)
                .gender("Male")
                .chiefComplaint("Crushing retrosternal chest pain radiating to left arm and jaw, profuse diaphoresis, sudden onset 40 mins ago")
                .vitalSigns("HR: 118 bpm, BP: 168/104 mmHg, SpO2: 92%, Temp: 37.1°C, RR: 24/min")
                .allergies("Penicillin")
                .medicalHistory("Coronary Artery Disease, Hypertension, Dyslipidemia, 30 pack-year smoking")
                .triageStatus(TriageStatus.INCOMING_TRIAGE)
                .triageRiskScore(88)
                .aiAcuityLevel("Level 1: Resuscitation (Critical)")
                .aiRiskFlags("HIGH ACUITY: Hypotension/Tachycardia risk; STEMI alert criteria met; Penicillin allergy flagged")
                .aiDifferentialDiagnosis("1. Acute ST-Elevation Myocardial Infarction (Anterior Wall STEMI)\n2. Acute Aortic Dissection (Stanford Type A)\n3. Massive Pulmonary Embolism")
                .aiSuggestedWorkup("12-Lead Stat ECG (< 10 min), High-sensitivity Troponin-I, Portable Chest X-Ray, Dual Antiplatelet Therapy (Aspirin + Ticagrelor)")
                .department(edTrauma)
                .assignedDoctor(clinicalDoctor)
                .admittedBy(nurse)
                .build());

        patientCaseRepository.save(PatientTriageCase.builder()
                .patientId("PT-9402")
                .patientName("Maria Garcia")
                .age(34)
                .gender("Female")
                .chiefComplaint("Acute respiratory distress with biphasic expiratory wheezing, severe dyspnea, non-responsive to home Albuterol MDI x3")
                .vitalSigns("HR: 124 bpm, BP: 138/88 mmHg, SpO2: 89%, Temp: 37.4°C, RR: 30/min")
                .allergies("Aspirin, NSAIDs")
                .medicalHistory("Severe Persistent Asthma, Chronic Allergic Rhinitis")
                .triageStatus(TriageStatus.AI_EVALUATED)
                .triageRiskScore(76)
                .aiAcuityLevel("Level 2: Emergent")
                .aiRiskFlags("Severe Hypoxemia (SpO2 89% on ambient air); Accessory muscle use; Aspirin-exacerbated respiratory disease risk")
                .aiDifferentialDiagnosis("1. Status Asthmaticus / Life-Threatening Acute Asthma Exacerbation\n2. Acute Bronchospasm with Viral Pneumonitis\n3. Spontaneous Pneumothorax")
                .aiSuggestedWorkup("Continuous DuoNeb (Albuterol + Ipratropium), IV Methylprednisolone 60mg, High-Flow O2 via non-rebreather, Bedside Ultrasound")
                .department(edTrauma)
                .assignedDoctor(clinicalDoctor)
                .admittedBy(nurse)
                .build());

        patientCaseRepository.save(PatientTriageCase.builder()
                .patientId("PT-9403")
                .patientName("Robert Taylor")
                .age(72)
                .gender("Male")
                .chiefComplaint("Acute right-sided hemiparesis, right facial droop, marked slurred speech (dysarthria/aphasia), onset 50 min ago")
                .vitalSigns("HR: 88 bpm, BP: 186/112 mmHg, SpO2: 97%, Temp: 36.8°C, RR: 18/min")
                .allergies("None recorded")
                .medicalHistory("Atrial Fibrillation, Type 2 Diabetes Mellitus, Prior TIA 3 years ago")
                .triageStatus(TriageStatus.PHYSICIAN_REVIEW)
                .triageRiskScore(89)
                .aiAcuityLevel("Level 1: Resuscitation (Critical)")
                .aiRiskFlags("CODE STROKE PRIORITY: Focal unilateral neurological deficit within thrombolytic time window (< 4.5 hrs); Accelerated HTN (186/112)")
                .aiDifferentialDiagnosis("1. Acute Ischemic Stroke (LVO - Left Middle Cerebral Artery suspect)\n2. Intracerebral Hemorrhage\n3. Hypoglycemic Mimic")
                .aiSuggestedWorkup("Emergency Non-contrast Head CT / CTA Head & Neck, Fingerstick Glucose stat, IV access x2, NIHSS score calculation")
                .department(neuroStroke)
                .assignedDoctor(clinicalDoctor)
                .admittedBy(nurse)
                .build());

        log.info("Clinical triage demo cases initialized.");
    }

    private void seedDoctorsAndAppointments() {
        if (doctorRepository.count() > 0) {
            log.info("Specialist doctors directory already initialized (count: {}).", doctorRepository.count());
            return;
        }

        log.info("Seeding verified Specialist Doctors directory (Muzaffarpur, Delhi, AIIMS Patna, IGIMS Patna, Medanta, etc.)...");

        List<Doctor> doctors = List.of(
                // ==================== MUZAFFARPUR (10 DOCTORS) ====================
                Doctor.builder()
                        .name("Dr. Navneet Kumar")
                        .specialty("Physician / Neuro, Diabetes, Liver & Thyroid")
                        .city("Muzaffarpur")
                        .hospital("Dr. Navneet Kumar Specialist Clinic")
                        .address("Kishore Complex, Prabhat Cinema Chowk, near Sahu Pokhar, Mahammadpur Kazi, Muzaffarpur, Bihar – 842002")
                        .designation("Senior Consultant Physician")
                        .qualifications("MBBS, MD (Medicine), Post-Graduate in Diabetology & Neuro Care")
                        .experienceYears(18)
                        .consultationFee(700)
                        .availableDays("Mon - Sat")
                        .availableTimeSlots("10:00 AM - 02:00 PM, 05:00 PM - 08:30 PM")
                        .rating(4.9)
                        .reviewCount(342)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Prakash Kumar Sinha")
                        .specialty("Neurology")
                        .city("Muzaffarpur")
                        .hospital("Prasad Hospital")
                        .address("Prasad Hospital, Brahmpura, Muzaffarpur, Bihar – 842003")
                        .designation("Senior Neurologist & Stroke Consultant")
                        .qualifications("MBBS, MD (General Medicine), DM (Neurology)")
                        .experienceYears(16)
                        .consultationFee(800)
                        .availableDays("Mon, Wed, Fri, Sat")
                        .availableTimeSlots("11:00 AM - 03:00 PM")
                        .rating(4.8)
                        .reviewCount(289)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Mayank Kumar")
                        .specialty("Neurosurgery & Spine")
                        .city("Muzaffarpur")
                        .hospital("Neuro Spine Center")
                        .address("Juran Chapra, Brahmapura, Muzaffarpur, Bihar – 842001")
                        .designation("Chief Consultant Neurosurgeon")
                        .qualifications("MBBS, MS (Surgery), MCh (Neurosurgery)")
                        .experienceYears(14)
                        .consultationFee(1000)
                        .availableDays("Mon - Sat")
                        .availableTimeSlots("02:00 PM - 07:00 PM")
                        .rating(4.8)
                        .reviewCount(210)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Amitesh Kumar")
                        .specialty("Gastroenterology / Liver Care")
                        .city("Muzaffarpur")
                        .hospital("Gastro & Liver Clinic")
                        .address("Hathi Chowk / Gaushala Road area, Muzaffarpur, Bihar – 842001")
                        .designation("Senior Consultant Gastroenterologist")
                        .qualifications("MBBS, MD (Medicine), DM (Gastroenterology)")
                        .experienceYears(15)
                        .consultationFee(800)
                        .availableDays("Mon - Fri")
                        .availableTimeSlots("10:30 AM - 02:30 PM, 05:30 PM - 08:00 PM")
                        .rating(4.9)
                        .reviewCount(315)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Shahabuddin Alam")
                        .specialty("Cardiology")
                        .city("Muzaffarpur")
                        .hospital("Heart Care & Diagnostic Clinic")
                        .address("Power House Road, near Circuit House, Maripur, Muzaffarpur, Bihar – 842001")
                        .designation("Consultant Interventional Cardiologist")
                        .qualifications("MBBS, MD (Medicine), PGDCC (Cardiology)")
                        .experienceYears(17)
                        .consultationFee(750)
                        .availableDays("Mon - Sat")
                        .availableTimeSlots("09:30 AM - 01:30 PM, 04:30 PM - 07:30 PM")
                        .rating(4.7)
                        .reviewCount(198)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Abhishek Mishra")
                        .specialty("Cardiology / Cardiovascular Care")
                        .city("Muzaffarpur")
                        .hospital("Narayan Heart Care Centre")
                        .address("Narayan Heart Care Centre, Juran Chhapra Main Road, Muzaffarpur, Bihar – 842001")
                        .designation("Director & Senior Cardiologist")
                        .qualifications("MBBS, MD (Medicine), DM (Cardiology)")
                        .experienceYears(16)
                        .consultationFee(900)
                        .availableDays("Mon - Sat")
                        .availableTimeSlots("10:00 AM - 03:00 PM")
                        .rating(4.9)
                        .reviewCount(420)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Upendra Prasad")
                        .specialty("Orthopedic Surgery / Joint Replacement")
                        .city("Muzaffarpur")
                        .hospital("Prasad Hospital")
                        .address("Prasad Hospital, Brahmpura, Muzaffarpur, Bihar – 842003")
                        .designation("Senior Orthopedic Surgeon & Medical Director")
                        .qualifications("MBBS, MS (Orthopaedics), MCh (Ortho)")
                        .experienceYears(24)
                        .consultationFee(800)
                        .availableDays("Mon - Sat")
                        .availableTimeSlots("10:00 AM - 02:00 PM, 05:00 PM - 08:00 PM")
                        .rating(4.8)
                        .reviewCount(380)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Dharmendra Prasad")
                        .specialty("Nephrology / Kidney Care")
                        .city("Muzaffarpur")
                        .hospital("Prasad Hospital")
                        .address("Prasad Hospital, Brahmpura, Muzaffarpur, Bihar – 842003")
                        .designation("Senior Consultant Nephrologist")
                        .qualifications("MBBS, MD (Medicine), DM (Nephrology)")
                        .experienceYears(15)
                        .consultationFee(850)
                        .availableDays("Mon, Wed, Fri")
                        .availableTimeSlots("11:30 AM - 04:00 PM")
                        .rating(4.8)
                        .reviewCount(175)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Abhimanyu Anat")
                        .specialty("Urology & Urological Surgery")
                        .city("Muzaffarpur")
                        .hospital("Prasad Hospital")
                        .address("Prasad Hospital, Brahmpura, Muzaffarpur, Bihar – 842003")
                        .designation("Consultant Urologist & Andrologist")
                        .qualifications("MBBS, MS (General Surgery), MCh (Urology)")
                        .experienceYears(13)
                        .consultationFee(800)
                        .availableDays("Tue, Thu, Sat")
                        .availableTimeSlots("12:00 PM - 05:00 PM")
                        .rating(4.7)
                        .reviewCount(142)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Ajit Kumar Sinha")
                        .specialty("General Medicine / Diabetology / Cardiology")
                        .city("Muzaffarpur")
                        .hospital("Diabetes & Cardio Clinic")
                        .address("Juran Chapra, Muzaffarpur, Bihar – 842001")
                        .designation("Senior General Physician & Diabetologist")
                        .qualifications("MBBS, MD (Medicine), FICA (USA)")
                        .experienceYears(22)
                        .consultationFee(700)
                        .availableDays("Mon - Sat")
                        .availableTimeSlots("09:00 AM - 01:00 PM, 05:00 PM - 08:00 PM")
                        .rating(4.8)
                        .reviewCount(260)
                        .verified(true)
                        .build(),

                // ==================== DELHI SENIOR SPECIALISTS / AIIMS NEW DELHI (10 DOCTORS) ====================
                Doctor.builder()
                        .name("Dr. Randeep Guleria")
                        .specialty("Pulmonology / Respiratory & Sleep Medicine")
                        .city("Delhi")
                        .hospital("Institute of Internal Medicine & Respiratory Medicine")
                        .address("Institute of Internal Medicine, Respiratory & Sleep Medicine, Delhi NCR")
                        .designation("Chairman & Senior Consultant (Former Director AIIMS New Delhi)")
                        .qualifications("MBBS, MD (Medicine), DM (Pulmonary Medicine), Padma Shri")
                        .experienceYears(35)
                        .consultationFee(2500)
                        .availableDays("Mon, Wed, Thu")
                        .availableTimeSlots("10:00 AM - 02:00 PM")
                        .rating(5.0)
                        .reviewCount(980)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Balram Bhargava")
                        .specialty("Cardiology & Cardiovascular Medicine")
                        .city("Delhi")
                        .hospital("AIIMS New Delhi")
                        .address("Department of Cardiology, AIIMS New Delhi, Ansari Nagar, New Delhi – 110029")
                        .designation("Professor of Cardiology (Former Director General, ICMR)")
                        .qualifications("MBBS, MD, DM (Cardiology), Padma Shri")
                        .experienceYears(34)
                        .consultationFee(2000)
                        .availableDays("Tue, Thu, Fri")
                        .availableTimeSlots("09:30 AM - 01:00 PM")
                        .rating(5.0)
                        .reviewCount(860)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Prabhjot Singh")
                        .specialty("Urology & Renal Transplant")
                        .city("Delhi")
                        .hospital("AIIMS New Delhi")
                        .address("AIIMS New Delhi, Ansari Nagar, New Delhi – 110029")
                        .designation("Professor & Senior Consultant Urologist")
                        .qualifications("MBBS, MS, MCh (Urology), DNB")
                        .experienceYears(19)
                        .consultationFee(1500)
                        .availableDays("Mon, Wed, Sat")
                        .availableTimeSlots("10:00 AM - 01:30 PM")
                        .rating(4.9)
                        .reviewCount(412)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Prabudh Goel")
                        .specialty("Pediatric Surgery & Pediatric Urology")
                        .city("Delhi")
                        .hospital("AIIMS New Delhi")
                        .address("AIIMS New Delhi, Ansari Nagar, New Delhi – 110029")
                        .designation("Additional Professor, Department of Pediatric Surgery")
                        .qualifications("MBBS, MS (Surgery), MCh (Pediatric Surgery)")
                        .experienceYears(17)
                        .consultationFee(1400)
                        .availableDays("Tue, Thu, Fri")
                        .availableTimeSlots("10:00 AM - 02:00 PM")
                        .rating(4.9)
                        .reviewCount(320)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Anu Sachdeva")
                        .specialty("Pediatrics & Pediatric Intensive Care")
                        .city("Delhi")
                        .hospital("AIIMS New Delhi")
                        .address("AIIMS New Delhi, Ansari Nagar, New Delhi – 110029")
                        .designation("Additional Professor of Pediatrics")
                        .qualifications("MBBS, MD (Pediatrics), Fellowship in Critical Care")
                        .experienceYears(18)
                        .consultationFee(1200)
                        .availableDays("Mon, Wed, Fri")
                        .availableTimeSlots("09:00 AM - 01:00 PM")
                        .rating(4.9)
                        .reviewCount(295)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Arvind Kumar")
                        .specialty("General Medicine & Internal Medicine")
                        .city("Delhi")
                        .hospital("AIIMS New Delhi")
                        .address("AIIMS New Delhi, Ansari Nagar, New Delhi – 110029")
                        .designation("Senior Professor of Medicine")
                        .qualifications("MBBS, MD (General Medicine)")
                        .experienceYears(25)
                        .consultationFee(1200)
                        .availableDays("Mon - Sat")
                        .availableTimeSlots("09:30 AM - 01:30 PM")
                        .rating(4.8)
                        .reviewCount(510)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Rishi Nayyar")
                        .specialty("Urology & Minimally Invasive Surgery")
                        .city("Delhi")
                        .hospital("AIIMS New Delhi")
                        .address("AIIMS New Delhi, Ansari Nagar, New Delhi – 110029")
                        .designation("Professor of Urology")
                        .qualifications("MBBS, MS, MCh (Urology)")
                        .experienceYears(18)
                        .consultationFee(1500)
                        .availableDays("Tue, Thu, Sat")
                        .availableTimeSlots("10:30 AM - 02:30 PM")
                        .rating(4.8)
                        .reviewCount(340)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. K. Aparna Sharma")
                        .specialty("Obstetrics & Gynecology / Fetal Medicine")
                        .city("Delhi")
                        .hospital("AIIMS New Delhi")
                        .address("AIIMS New Delhi, Ansari Nagar, New Delhi – 110029")
                        .designation("Professor, Department of Obstetrics & Gynecology")
                        .qualifications("MBBS, MD (Obstetrics & Gynecology), DNB")
                        .experienceYears(20)
                        .consultationFee(1400)
                        .availableDays("Mon, Wed, Fri")
                        .availableTimeSlots("09:30 AM - 01:30 PM")
                        .rating(4.9)
                        .reviewCount(470)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Y.C. Porwal")
                        .specialty("General Medicine")
                        .city("Delhi")
                        .hospital("VMMC & Safdarjung Hospital")
                        .address("Ring Road, Ansari Nagar West, New Delhi – 110029")
                        .designation("Professor & Senior Consultant, Department of Medicine")
                        .qualifications("MBBS, MD (Medicine)")
                        .experienceYears(28)
                        .consultationFee(1000)
                        .availableDays("Mon, Wed, Fri")
                        .availableTimeSlots("09:00 AM - 01:00 PM")
                        .rating(4.8)
                        .reviewCount(380)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Rupali Malik")
                        .specialty("General Medicine & Clinical Therapeutics")
                        .city("Delhi")
                        .hospital("VMMC & Safdarjung Hospital")
                        .address("Ring Road, Ansari Nagar West, New Delhi – 110029")
                        .designation("Senior Consultant Physician")
                        .qualifications("MBBS, MD (Medicine)")
                        .experienceYears(17)
                        .consultationFee(900)
                        .availableDays("Tue, Thu, Sat")
                        .availableTimeSlots("09:30 AM - 01:30 PM")
                        .rating(4.8)
                        .reviewCount(260)
                        .verified(true)
                        .build(),

                // ==================== SAFDARJUNG HOSPITAL, DELHI ====================
                Doctor.builder()
                        .name("Dr. Shivlok Narayan Ambedkar")
                        .specialty("General Medicine")
                        .city("Delhi")
                        .hospital("VMMC & Safdarjung Hospital")
                        .address("Ring Road, Ansari Nagar West, New Delhi – 110029")
                        .designation("Senior Specialist & Physician")
                        .qualifications("MBBS, MD (Internal Medicine)")
                        .experienceYears(16)
                        .consultationFee(850)
                        .availableDays("Mon - Fri")
                        .availableTimeSlots("09:30 AM - 01:30 PM")
                        .rating(4.7)
                        .reviewCount(190)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Sandeep Kumar")
                        .specialty("Pediatrics & Neonatology")
                        .city("Delhi")
                        .hospital("VMMC & Safdarjung Hospital")
                        .address("Ring Road, Ansari Nagar West, New Delhi – 110029")
                        .designation("Senior Specialist, Department of Pediatrics")
                        .qualifications("MBBS, MD (Pediatrics)")
                        .experienceYears(18)
                        .consultationFee(850)
                        .availableDays("Mon, Wed, Fri")
                        .availableTimeSlots("09:00 AM - 01:00 PM")
                        .rating(4.8)
                        .reviewCount(215)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Shobha Sharma")
                        .specialty("Pediatrics")
                        .city("Delhi")
                        .hospital("VMMC & Safdarjung Hospital")
                        .address("Ring Road, Ansari Nagar West, New Delhi – 110029")
                        .designation("Consultant Pediatrician")
                        .qualifications("MBBS, MD (Pediatrics), DCH")
                        .experienceYears(19)
                        .consultationFee(850)
                        .availableDays("Tue, Thu, Sat")
                        .availableTimeSlots("09:30 AM - 01:30 PM")
                        .rating(4.8)
                        .reviewCount(240)
                        .verified(true)
                        .build(),

                // ==================== AIIMS PATNA (5 DOCTORS) ====================
                Doctor.builder()
                        .name("Dr. Anupam Bhambhani")
                        .specialty("Cardiology")
                        .city("Patna")
                        .hospital("AIIMS Patna")
                        .address("AIIMS Patna, Phulwarisharif, Patna, Bihar – 801507")
                        .designation("Additional Professor & Head, Department of Cardiology")
                        .qualifications("MBBS, MD (Medicine), DM (Cardiology)")
                        .experienceYears(20)
                        .consultationFee(1200)
                        .availableDays("Mon, Wed, Fri")
                        .availableTimeSlots("09:30 AM - 01:30 PM")
                        .rating(4.9)
                        .reviewCount(460)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Sanjeev Kumar")
                        .specialty("Cardiothoracic & Vascular Surgery (CTVS)")
                        .city("Patna")
                        .hospital("AIIMS Patna")
                        .address("AIIMS Patna, Phulwarisharif, Patna, Bihar – 801507")
                        .designation("Professor & Head, Department of CTVS")
                        .qualifications("MBBS, MS (Surgery), MCh (CTVS)")
                        .experienceYears(22)
                        .consultationFee(1500)
                        .availableDays("Tue, Thu, Sat")
                        .availableTimeSlots("10:00 AM - 02:00 PM")
                        .rating(4.9)
                        .reviewCount(380)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Arun Prasad")
                        .specialty("Pediatrics / Clinical Haematology")
                        .city("Patna")
                        .hospital("AIIMS Patna")
                        .address("AIIMS Patna, Phulwarisharif, Patna, Bihar – 801507")
                        .designation("Professor, Department of Pediatrics")
                        .qualifications("MBBS, MD (Pediatrics), Fellowship in Clinical Haematology")
                        .experienceYears(23)
                        .consultationFee(1100)
                        .availableDays("Mon, Wed, Fri")
                        .availableTimeSlots("09:00 AM - 01:00 PM")
                        .rating(4.8)
                        .reviewCount(290)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Pankaj Kumar")
                        .specialty("Nuclear Medicine & Molecular Imaging")
                        .city("Patna")
                        .hospital("AIIMS Patna")
                        .address("AIIMS Patna, Phulwarisharif, Patna, Bihar – 801507")
                        .designation("Faculty & Head, Department of Nuclear Medicine")
                        .qualifications("MBBS, MD (Nuclear Medicine), DNB")
                        .experienceYears(15)
                        .consultationFee(1200)
                        .availableDays("Mon - Fri")
                        .availableTimeSlots("10:00 AM - 02:00 PM")
                        .rating(4.8)
                        .reviewCount(175)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Kunal Singh")
                        .specialty("Anaesthesiology & Neurocritical Care")
                        .city("Patna")
                        .hospital("AIIMS Patna")
                        .address("AIIMS Patna, Phulwarisharif, Patna, Bihar – 801507")
                        .designation("Additional Professor, Department of Anaesthesiology")
                        .qualifications("MBBS, MD (Anaesthesiology), PDCC (Neuroanaesthesia)")
                        .experienceYears(17)
                        .consultationFee(1000)
                        .availableDays("Tue, Thu, Sat")
                        .availableTimeSlots("09:30 AM - 01:30 PM")
                        .rating(4.8)
                        .reviewCount(195)
                        .verified(true)
                        .build(),

                // ==================== IGIMS PATNA (5 DOCTORS) ====================
                Doctor.builder()
                        .name("Prof. (Dr.) Ravi Vishnu Prasad")
                        .specialty("Cardiology")
                        .city("Patna")
                        .hospital("IGIMS Patna")
                        .address("IGIMS, Sheikhpura, Patna, Bihar – 800014")
                        .designation("Senior Professor of Cardiology")
                        .qualifications("MBBS, MD, DM (Cardiology)")
                        .experienceYears(26)
                        .consultationFee(1200)
                        .availableDays("Mon, Wed, Fri")
                        .availableTimeSlots("09:30 AM - 01:30 PM")
                        .rating(4.9)
                        .reviewCount(510)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Prof. (Dr.) Nirav Kumar")
                        .specialty("Cardiology / Electrophysiology")
                        .city("Patna")
                        .hospital("IGIMS Patna")
                        .address("IGIMS, Sheikhpura, Patna, Bihar – 800014")
                        .designation("Professor of Cardiology")
                        .qualifications("MBBS, MD, DM (Cardiology)")
                        .experienceYears(22)
                        .consultationFee(1100)
                        .availableDays("Tue, Thu, Sat")
                        .availableTimeSlots("09:30 AM - 01:30 PM")
                        .rating(4.9)
                        .reviewCount(430)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Goutam Kumar")
                        .specialty("Cardiology")
                        .city("Patna")
                        .hospital("IGIMS Patna")
                        .address("IGIMS, Sheikhpura, Patna, Bihar – 800014")
                        .designation("Associate Professor, Department of Cardiology")
                        .qualifications("MBBS, MD (Medicine), DM (Cardiology)")
                        .experienceYears(15)
                        .consultationFee(950)
                        .availableDays("Mon - Fri")
                        .availableTimeSlots("10:00 AM - 02:00 PM")
                        .rating(4.8)
                        .reviewCount(270)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Prof. (Dr.) Sudhir Kumar")
                        .specialty("General Medicine")
                        .city("Patna")
                        .hospital("IGIMS Patna")
                        .address("IGIMS, Sheikhpura, Patna, Bihar – 800014")
                        .designation("Professor, Department of General Medicine")
                        .qualifications("MBBS, MD (General Medicine)")
                        .experienceYears(24)
                        .consultationFee(900)
                        .availableDays("Mon - Sat")
                        .availableTimeSlots("09:00 AM - 01:00 PM")
                        .rating(4.8)
                        .reviewCount(350)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Prof. (Dr.) Rajesh Kumar")
                        .specialty("Psychiatry & Behavioral Health")
                        .city("Patna")
                        .hospital("IGIMS Patna")
                        .address("IGIMS, Sheikhpura, Patna, Bihar – 800014")
                        .designation("Professor & Dean (Research), Department of Psychiatry")
                        .qualifications("MBBS, MD (Psychiatry)")
                        .experienceYears(27)
                        .consultationFee(1100)
                        .availableDays("Mon, Wed, Fri")
                        .availableTimeSlots("10:00 AM - 02:00 PM")
                        .rating(4.9)
                        .reviewCount(410)
                        .verified(true)
                        .build(),

                // ==================== MEDANTA / JAY PRABHA MEDANTA PATNA ====================
                Doctor.builder()
                        .name("Dr. Ajay Kumar Sinha")
                        .specialty("Cardiology / Electrophysiology")
                        .city("Patna")
                        .hospital("Jay Prabha Medanta Super Specialty Hospital")
                        .address("Housing Board Colony, Kankarbagh, Patrakar Nagar, Patna, Bihar – 800020")
                        .designation("Director & Senior Consultant, Cardiac Care")
                        .qualifications("MBBS, MD, DM (Cardiology), FACC (USA)")
                        .experienceYears(26)
                        .consultationFee(1800)
                        .availableDays("Mon - Sat")
                        .availableTimeSlots("10:00 AM - 03:00 PM")
                        .rating(4.9)
                        .reviewCount(620)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Arvind Kumar Goyal")
                        .specialty("Cardiothoracic & Vascular Surgery (CTVS)")
                        .city("Patna")
                        .hospital("Jay Prabha Medanta Super Specialty Hospital")
                        .address("Housing Board Colony, Kankarbagh, Patrakar Nagar, Patna, Bihar – 800020")
                        .designation("Director, Cardiac & Robotic Thoracic Surgery")
                        .qualifications("MBBS, MS (Surgery), MCh (CTVS), Fellowship Adult Cardiac Surgery (USA)")
                        .experienceYears(24)
                        .consultationFee(2000)
                        .availableDays("Mon - Fri")
                        .availableTimeSlots("10:30 AM - 03:30 PM")
                        .rating(4.9)
                        .reviewCount(540)
                        .verified(true)
                        .build(),

                Doctor.builder()
                        .name("Dr. Alankrita Aishwarya")
                        .specialty("Anaesthesiology & Critical Care")
                        .city("Patna")
                        .hospital("Jay Prabha Medanta Super Specialty Hospital")
                        .address("Housing Board Colony, Kankarbagh, Patrakar Nagar, Patna, Bihar – 800020")
                        .designation("Associate Director, Critical Care & Anaesthesia")
                        .qualifications("MBBS, MD (Anaesthesiology), IDCCM")
                        .experienceYears(16)
                        .consultationFee(1200)
                        .availableDays("Mon - Sat")
                        .availableTimeSlots("09:00 AM - 02:00 PM")
                        .rating(4.8)
                        .reviewCount(210)
                        .verified(true)
                        .build(),

                // ==================== KHAN SIR HOSPITAL / KHAN HEALTHCARE PATNA ====================
                Doctor.builder()
                        .name("Dr. Pankaj Kumar")
                        .specialty("Cardiology")
                        .city("Patna")
                        .hospital("Khan Healthcare / Khan Sir Hospital")
                        .address("Ashok Rajpath Road, Gandhi Maidan area, Patna, Bihar – 800001/800004")
                        .designation("Consultant Cardiologist")
                        .qualifications("MBBS, MD (Medicine), Cardiology Specialist")
                        .experienceYears(12)
                        .consultationFee(500)
                        .availableDays("Mon - Sat")
                        .availableTimeSlots("10:00 AM - 02:00 PM, 05:00 PM - 08:00 PM")
                        .rating(4.7)
                        .reviewCount(380)
                        .verified(true)
                        .verificationNote("Patient Advisory: Publicly available physician credential records vary. Please confirm doctor's current OPD shift and verification directly at facility reception before visiting.")
                        .build(),

                Doctor.builder()
                        .name("Senior Cardiology Specialist")
                        .specialty("Cardiology / General Cardiac Care")
                        .city("Patna")
                        .hospital("Khan Sir Hospital / Khan Healthcare")
                        .address("Ashok Rajpath Road, Gandhi Maidan area, Patna, Bihar – 800001")
                        .designation("Department of Cardiology Specialist")
                        .qualifications("MBBS, Clinical Cardiology Fellowship")
                        .experienceYears(10)
                        .consultationFee(400)
                        .availableDays("Mon - Sat")
                        .availableTimeSlots("10:00 AM - 01:00 PM")
                        .rating(4.6)
                        .reviewCount(190)
                        .verified(true)
                        .verificationNote("Institutional Faculty Post. Confirm current on-duty consultant at the reception desk.")
                        .build(),

                Doctor.builder()
                        .name("Orthopedic Specialist")
                        .specialty("Orthopedics & Fracture Care")
                        .city("Patna")
                        .hospital("Khan Sir Hospital / Khan Healthcare")
                        .address("Ashok Rajpath Road, Gandhi Maidan area, Patna, Bihar – 800001")
                        .designation("Department of Orthopedics")
                        .qualifications("MBBS, MS (Orthopedics)")
                        .experienceYears(11)
                        .consultationFee(400)
                        .availableDays("Mon, Wed, Fri")
                        .availableTimeSlots("11:00 AM - 03:00 PM")
                        .rating(4.6)
                        .reviewCount(210)
                        .verified(true)
                        .verificationNote("Institutional Faculty Post. Confirm current on-duty consultant at the reception desk.")
                        .build(),

                Doctor.builder()
                        .name("Gynecology / Obstetrics Specialist")
                        .specialty("Obstetrics & Gynecology / Maternity")
                        .city("Patna")
                        .hospital("Khan Sir Hospital / Khan Healthcare")
                        .address("Ashok Rajpath Road, Gandhi Maidan area, Patna, Bihar – 800001")
                        .designation("Department of Maternity & Gynecology")
                        .qualifications("MBBS, DGO, MS (OBGYN)")
                        .experienceYears(14)
                        .consultationFee(450)
                        .availableDays("Mon - Sat")
                        .availableTimeSlots("09:30 AM - 01:30 PM")
                        .rating(4.7)
                        .reviewCount(340)
                        .verified(true)
                        .verificationNote("Institutional Faculty Post. Confirm current on-duty consultant at the reception desk.")
                        .build(),

                Doctor.builder()
                        .name("General Medicine Specialist")
                        .specialty("General Medicine / Multi-Specialty Care")
                        .city("Patna")
                        .hospital("Khan Sir Hospital / Khan Healthcare")
                        .address("Ashok Rajpath Road, Gandhi Maidan area, Patna, Bihar – 800001")
                        .designation("Department of General Medicine")
                        .qualifications("MBBS, MD (Medicine)")
                        .experienceYears(13)
                        .consultationFee(350)
                        .availableDays("All Days")
                        .availableTimeSlots("09:00 AM - 01:00 PM, 04:00 PM - 08:00 PM")
                        .rating(4.7)
                        .reviewCount(420)
                        .verified(true)
                        .verificationNote("Institutional Faculty Post. Confirm current on-duty consultant at the reception desk.")
                        .build()
        );

        List<Doctor> savedDoctors = doctorRepository.saveAll(doctors);
        log.info("Successfully seeded {} specialist doctors across Muzaffarpur, Delhi, and Patna.", savedDoctors.size());

        // Pre-seed sample confirmed appointment bookings
        Doctor drNavneet = savedDoctors.stream()
                .filter(d -> d.getName().contains("Navneet"))
                .findFirst()
                .orElse(savedDoctors.get(0));

        Doctor drGuleria = savedDoctors.stream()
                .filter(d -> d.getName().contains("Guleria"))
                .findFirst()
                .orElse(savedDoctors.get(1));

        Doctor drBhambhani = savedDoctors.stream()
                .filter(d -> d.getName().contains("Bhambhani"))
                .findFirst()
                .orElse(savedDoctors.get(2));

        appointmentRepository.save(Appointment.builder()
                .bookingReference("MED-APT-1042")
                .doctorId(drNavneet.getId())
                .doctorName(drNavneet.getName())
                .doctorSpecialty(drNavneet.getSpecialty())
                .hospital(drNavneet.getHospital())
                .city(drNavneet.getCity())
                .address(drNavneet.getAddress())
                .patientName("Rameshwar Sharma")
                .patientPhone("+91 98350 21984")
                .patientEmail("rameshwar.sharma@example.com")
                .patientAge(52)
                .patientGender("Male")
                .appointmentDate(LocalDate.now().plusDays(1))
                .timeSlot("10:30 AM")
                .symptoms("Uncontrolled type-2 diabetes fasting sugar > 220 mg/dL with peripheral neuropathy tingling in feet.")
                .status("CONFIRMED")
                .consultationFee(drNavneet.getConsultationFee())
                .build());

        appointmentRepository.save(Appointment.builder()
                .bookingReference("MED-APT-1088")
                .doctorId(drGuleria.getId())
                .doctorName(drGuleria.getName())
                .doctorSpecialty(drGuleria.getSpecialty())
                .hospital(drGuleria.getHospital())
                .city(drGuleria.getCity())
                .address(drGuleria.getAddress())
                .patientName("Sunita Devi")
                .patientPhone("+91 94312 87654")
                .patientEmail("sunita.devi@example.com")
                .patientAge(61)
                .patientGender("Female")
                .appointmentDate(LocalDate.now().plusDays(2))
                .timeSlot("11:30 AM")
                .symptoms("Chronic persistent dry cough and exertional breathlessness for 4 months.")
                .status("CONFIRMED")
                .consultationFee(drGuleria.getConsultationFee())
                .build());

        appointmentRepository.save(Appointment.builder()
                .bookingReference("MED-APT-1124")
                .doctorId(drBhambhani.getId())
                .doctorName(drBhambhani.getName())
                .doctorSpecialty(drBhambhani.getSpecialty())
                .hospital(drBhambhani.getHospital())
                .city(drBhambhani.getCity())
                .address(drBhambhani.getAddress())
                .patientName("Amitabh Kumar Verma")
                .patientPhone("+91 91234 56789")
                .patientEmail("amitabh.verma@example.com")
                .patientAge(48)
                .patientGender("Male")
                .appointmentDate(LocalDate.now().plusDays(3))
                .timeSlot("10:00 AM")
                .symptoms("Post-angioplasty 6-month routine cardiology follow-up and ECG check.")
                .status("CONFIRMED")
                .consultationFee(drBhambhani.getConsultationFee())
                .build());

        log.info("Pre-seeded sample confirmed appointments.");
    }
}
